# Generated by Django 5.0.3 on 2024-04-30 06:02

import configurations.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True, verbose_name='الإسم')),
                ('type', models.CharField(choices=[('mcdi', 'MCDI'), ('surgard', 'SurGard')], max_length=10, verbose_name='النوع')),
                ('com', models.CharField(choices=configurations.utils.get_ports, max_length=30, unique=True, verbose_name='COM')),
                ('baud_rate', models.IntegerField(choices=[(9600, '9600'), (11440, '11440'), (19200, '19200'), (115200, '115200')], default=9600, verbose_name='Baud Rate')),
                ('end_line', models.CharField(choices=[('<CR>', '<CR>'), ('<DC4>', '<DC4>')], max_length=10, verbose_name='End Line')),
            ],
            options={
                'verbose_name': 'الجهاز',
                'verbose_name_plural': 'الأجهزة',
            },
        ),
        migrations.CreateModel(
            name='AlarmCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='القسم')),
                ('code', models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator(message='الرمز غير صحيح', regex='^[ER](\\d+)$')], verbose_name='الرمز')),
                ('description', models.CharField(max_length=40, verbose_name='الوصف')),
                ('decryption_type', models.IntegerField(choices=[(0, 'المنطقة'), (1, 'المستهلك')], default=0, verbose_name='نوع فك التشفير')),
                ('alarm_type', models.IntegerField(choices=[(0, 'لا يوجد'), (1, 'تسجيل تلقائي'), (2, 'تجربة تلقائية'), (4, 'فتح'), (5, 'إغلاق')], default=0, verbose_name='Alarm Type')),
                ('has_return', models.BooleanField(default=False, verbose_name='يوجد حدث عودة')),
                ('return_delay_minutes', models.PositiveIntegerField(default=0, verbose_name='دقيقة')),
                ('return_delay_hours', models.PositiveIntegerField(default=0, verbose_name='ساعة')),
                ('is_periodic', models.BooleanField(default=False, verbose_name='مجدول')),
                ('periodic_interval_minutes', models.PositiveIntegerField(default=0, verbose_name='دقيقة')),
                ('periodic_interval_hours', models.PositiveIntegerField(default=0, verbose_name='ساعة')),
                ('action_101', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_102', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_103', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_104', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_105', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_106', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_107', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_108', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_109', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_110', models.IntegerField(default=0, verbose_name='الإجراء الأول')),
                ('action_201', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_202', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_203', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_204', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_205', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_206', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_207', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_208', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_209', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('action_210', models.IntegerField(default=0, verbose_name='الإجراء الثاني')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_codes', to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'رمز الإنذار',
                'verbose_name_plural': 'الإنذارات',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='القسم')),
                ('is_open_saturday', models.BooleanField(default=False, verbose_name='السبت')),
                ('opening_saturday', models.TimeField(blank=True, null=True, verbose_name='فتح')),
                ('delay_opning_saturday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('closing_saturday', models.TimeField(blank=True, null=True, verbose_name='إغلاق')),
                ('delay_closing_saturday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('is_open_sunday', models.BooleanField(default=False, verbose_name='الأحد')),
                ('opening_sunday', models.TimeField(blank=True, null=True, verbose_name='فتح')),
                ('delay_opning_sunday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('closing_sunday', models.TimeField(blank=True, null=True, verbose_name='إغلاق')),
                ('delay_closing_sunday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('is_open_monday', models.BooleanField(default=False, verbose_name='الاثنين')),
                ('opening_monday', models.TimeField(blank=True, null=True, verbose_name='فتح')),
                ('delay_opning_monday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('closing_monday', models.TimeField(blank=True, null=True, verbose_name='إغلاق')),
                ('delay_closing_monday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('is_open_tuesday', models.BooleanField(default=False, verbose_name='الثلاثاء')),
                ('opening_tuesday', models.TimeField(blank=True, null=True, verbose_name='فتح')),
                ('delay_opning_tuesday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('closing_tuesday', models.TimeField(blank=True, null=True, verbose_name='إغلاق')),
                ('delay_closing_tuesday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('is_open_wednesday', models.BooleanField(default=False, verbose_name='الأربعاء')),
                ('opening_wednesday', models.TimeField(blank=True, null=True, verbose_name='فتح')),
                ('delay_opning_wednesday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('closing_wednesday', models.TimeField(blank=True, null=True, verbose_name='إغلاق')),
                ('delay_closing_wednesday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('is_open_thursday', models.BooleanField(default=False, verbose_name='الخميس')),
                ('opening_thursday', models.TimeField(blank=True, null=True, verbose_name='فتح')),
                ('delay_opning_thursday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('closing_thursday', models.TimeField(blank=True, null=True, verbose_name='إغلاق')),
                ('delay_closing_thursday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('is_open_friday', models.BooleanField(default=False, verbose_name='الجمعة')),
                ('opening_friday', models.TimeField(blank=True, null=True, verbose_name='فتح')),
                ('delay_opning_friday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('closing_friday', models.TimeField(blank=True, null=True, verbose_name='إغلاق')),
                ('delay_closing_friday', models.IntegerField(default=0, verbose_name='التأخير')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'الجدول',
                'verbose_name_plural': 'الجداول',
            },
        ),
        migrations.AddConstraint(
            model_name='alarmcode',
            constraint=models.UniqueConstraint(fields=('account', 'partition', 'code'), name='configurations.alarmcode.unique_id'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('account', 'partition'), name='configurations.schedule.unique_id'),
        ),
    ]
