# Generated by Django 5.0.3 on 2024-03-14 23:30

import configurations.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmCode',
            fields=[
                ('code', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='DecryptionConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('decryption_mask', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('com', models.CharField(blank=True, choices=configurations.utils.get_ports, max_length=30, unique=True)),
                ('baud_rate', models.IntegerField(default=9600)),
                ('end_line', models.CharField(choices=[('<CR>', '<CR>'), ('<DC4>', '<DC4>')], max_length=10)),
                ('decryption_configurations', models.ManyToManyField(null=True, to='configurations.decryptionconfiguration')),
            ],
        ),
    ]
