# Generated by Django 5.0.3 on 2024-03-14 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptionconfiguration',
            name='end_line',
        ),
        migrations.AddField(
            model_name='device',
            name='end_line',
            field=models.CharField(choices=[('<CR>', '<CR>'), ('<DC4>', '<DC4>')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
