# Generated by Django 5.0.3 on 2024-03-15 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmcode',
            name='type',
            field=models.IntegerField(choices=[(0, 'Zone'), (1, 'User')], default=0),
        ),
    ]
