# Generated by Django 5.0.3 on 2024-03-18 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0002_remove_alarmcode_name_alarmcode_delay_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmcode',
            name='delay',
        ),
        migrations.RemoveField(
            model_name='alarmcode',
            name='priority',
        ),
    ]
