# Generated by Django 5.0.3 on 2024-04-19 12:23

import configurations.utils
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options_alter_accountuser_options_and_more'),
        ('configurations', '0005_rename_type_alarmcode_decryption_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmcode',
            options={'verbose_name': 'Alarm Code', 'verbose_name_plural': 'Alarm Codes'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'Device', 'verbose_name_plural': 'Devices'},
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='code',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message='Code does not comply', regex='^[ER](\\d+)$')], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='decryption_type',
            field=models.IntegerField(choices=[(0, 'Zone'), (1, 'User')], default=0, verbose_name='Decryption Type'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='description',
            field=models.CharField(max_length=40, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='partition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Partition'),
        ),
        migrations.AlterField(
            model_name='device',
            name='baud_rate',
            field=models.IntegerField(choices=[(9600, '9600'), (11440, '11440'), (19200, '19200'), (115200, '115200')], default=9600, verbose_name='Baud Rate'),
        ),
        migrations.AlterField(
            model_name='device',
            name='com',
            field=models.CharField(choices=configurations.utils.get_ports, max_length=30, unique=True, verbose_name='COM'),
        ),
        migrations.AlterField(
            model_name='device',
            name='end_line',
            field=models.CharField(choices=[('<CR>', '<CR>'), ('<DC4>', '<DC4>')], max_length=10, verbose_name='End Line'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('mcdi', 'MCDI'), ('surgard', 'SurGard')], max_length=10, verbose_name='Type'),
        ),
    ]
