# Generated by Django 5.0.3 on 2024-04-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_alter_city_options_and_more'),
        ('configurations', '0006_alter_alarmcode_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmcode',
            options={'verbose_name': 'Alarm Code', 'verbose_name_plural': 'الإنذارات'},
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='alarm_type',
            field=models.IntegerField(choices=[(0, 'بلا'), (1, 'Auto Log'), (2, 'Auto Test'), (3, 'Gaurd Round'), (4, 'Opening'), (5, 'Closing')], default=0, verbose_name='Alarm Type'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='decryption_type',
            field=models.IntegerField(choices=[(0, 'Zone'), (1, 'المستخدم')], default=0, verbose_name='Decryption Type'),
        ),
    ]
