# Generated by Django 5.0.3 on 2024-04-25 14:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_account_copy_alarm_codes_and_more'),
        ('configurations', '0007_alter_alarmcode_options_alarmcode_alarm_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmcode',
            name='action_101',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_102',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_103',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_104',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_105',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_106',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_107',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_108',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_109',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_110',
            field=models.IntegerField(default=0, verbose_name='Action 1'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_201',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_202',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_203',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_204',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_205',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_206',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_207',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_208',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_209',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='action_210',
            field=models.IntegerField(default=0, verbose_name='Action 2'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='is_periodic',
            field=models.BooleanField(default=False, verbose_name='Scheduled'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='periodic_interval_hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='periodic_interval_minutes',
            field=models.IntegerField(default=0, verbose_name='Minutes'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='return_delay',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='alarm_type',
            field=models.IntegerField(choices=[(0, 'بلا'), (1, 'Auto Log'), (2, 'Auto Test'), (4, 'Opening'), (5, 'Closing')], default=0, verbose_name='Alarm Type'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='code',
            field=models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator(message='Code does not comply', regex='^[ER](\\d+)$')], verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='partition',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Partition'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Partition')),
                ('is_open_saturday', models.BooleanField(default=False, verbose_name='Open Saturday')),
                ('opening_saturday', models.TimeField(blank=True, null=True, verbose_name='Opening Saturday')),
                ('delay_opning_saturday', models.IntegerField(default=0, verbose_name='Delay Open Saturday')),
                ('closing_saturday', models.TimeField(blank=True, null=True, verbose_name='Closing Saturday')),
                ('delay_closing_saturday', models.IntegerField(default=0, verbose_name='Delay Open Saturday')),
                ('is_open_sunday', models.BooleanField(default=False, verbose_name='Open Sunday')),
                ('opening_sunday', models.TimeField(blank=True, null=True, verbose_name='Opening Sunday')),
                ('delay_opning_sunday', models.IntegerField(default=0, verbose_name='Delay Open Sunday')),
                ('closing_sunday', models.TimeField(blank=True, null=True, verbose_name='Closing Sunday')),
                ('delay_closing_sunday', models.IntegerField(default=0, verbose_name='Delay Open Sunday')),
                ('is_open_monday', models.BooleanField(default=False, verbose_name='Open Monday')),
                ('opening_monday', models.TimeField(blank=True, null=True, verbose_name='Opening Monday')),
                ('delay_opning_monday', models.IntegerField(default=0, verbose_name='Delay Open Monday')),
                ('closing_monday', models.TimeField(blank=True, null=True, verbose_name='Closing Monday')),
                ('delay_closing_monday', models.IntegerField(default=0, verbose_name='Delay Open Monday')),
                ('is_open_tuesday', models.BooleanField(default=False, verbose_name='Open Tuesday')),
                ('opening_tuesday', models.TimeField(blank=True, null=True, verbose_name='Opening Tuesday')),
                ('delay_opning_tuesday', models.IntegerField(default=0, verbose_name='Delay Open Tuesday')),
                ('closing_tuesday', models.TimeField(blank=True, null=True, verbose_name='Closing Tuesday')),
                ('delay_closing_tuesday', models.IntegerField(default=0, verbose_name='Delay Open Tuesday')),
                ('is_open_wednesday', models.BooleanField(default=False, verbose_name='Open Wednesday')),
                ('opening_wednesday', models.TimeField(blank=True, null=True, verbose_name='Opening Wednesday')),
                ('delay_opning_wednesday', models.IntegerField(default=0, verbose_name='Delay Open Wednesday')),
                ('closing_wednesday', models.TimeField(blank=True, null=True, verbose_name='Closing Wednesday')),
                ('delay_closing_wednesday', models.IntegerField(default=0, verbose_name='Delay Open Wednesday')),
                ('is_open_thursday', models.BooleanField(default=False, verbose_name='Open Thursday')),
                ('opening_thursday', models.TimeField(blank=True, null=True, verbose_name='Opening Thursday')),
                ('delay_opning_thursday', models.IntegerField(default=0, verbose_name='Delay Open Thursday')),
                ('closing_thursday', models.TimeField(blank=True, null=True, verbose_name='Closing Thursday')),
                ('delay_closing_thursday', models.IntegerField(default=0, verbose_name='Delay Open Thursday')),
                ('is_open_friday', models.BooleanField(default=False, verbose_name='Open Friday')),
                ('opening_friday', models.TimeField(blank=True, null=True, verbose_name='Opening Friday')),
                ('delay_opning_friday', models.IntegerField(default=0, verbose_name='Delay Open Friday')),
                ('closing_friday', models.TimeField(blank=True, null=True, verbose_name='Closing Friday')),
                ('delay_closing_friday', models.IntegerField(default=0, verbose_name='Delay Open Friday')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
            },
        ),
    ]
