# Generated by Django 5.0.3 on 2024-04-26 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_historicalaccount_options_and_more'),
        ('configurations', '0008_alarmcode_action_101_alarmcode_action_102_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alarmcode',
            name='configurations.alarmcode.unique_id',
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='periodic_interval_hours',
            field=models.IntegerField(default=0, verbose_name='ساعة'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='periodic_interval_minutes',
            field=models.IntegerField(default=0, verbose_name='دقيقة'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_friday',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_monday',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_saturday',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_sunday',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_thursday',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_tuesday',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_wednesday',
            field=models.TimeField(blank=True, null=True, verbose_name='Closing'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_friday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_monday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_saturday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_sunday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_thursday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_tuesday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_wednesday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_friday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_monday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_saturday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_sunday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_thursday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_tuesday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_wednesday',
            field=models.IntegerField(default=0, verbose_name='Delay'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_open_friday',
            field=models.BooleanField(default=False, verbose_name='الجمعة'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_open_monday',
            field=models.BooleanField(default=False, verbose_name='الاثنين'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_open_saturday',
            field=models.BooleanField(default=False, verbose_name='السبت'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_open_sunday',
            field=models.BooleanField(default=False, verbose_name='الأحد'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_open_thursday',
            field=models.BooleanField(default=False, verbose_name='الخميس'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_open_tuesday',
            field=models.BooleanField(default=False, verbose_name='الثلاثاء'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='is_open_wednesday',
            field=models.BooleanField(default=False, verbose_name='الأربعاء'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_friday',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_monday',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_saturday',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_sunday',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_thursday',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_tuesday',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_wednesday',
            field=models.TimeField(blank=True, null=True, verbose_name='Opening'),
        ),
        migrations.AddConstraint(
            model_name='alarmcode',
            constraint=models.UniqueConstraint(fields=('account', 'partition', 'code'), name='configurations.alarmcode.unique_id'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.UniqueConstraint(fields=('account', 'partition'), name='configurations.schedule.unique_id'),
        ),
    ]
