# Generated by Django 5.0.3 on 2024-04-27 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0009_remove_alarmcode_configurations_alarmcode_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alarmcode',
            options={'verbose_name': 'رمز الإنذار', 'verbose_name_plural': 'الإنذارات'},
        ),
        migrations.AlterModelOptions(
            name='device',
            options={'verbose_name': 'الجهاز', 'verbose_name_plural': 'الأجهزة'},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'verbose_name': 'الجدول', 'verbose_name_plural': 'الجداول'},
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_101',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_102',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_103',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_104',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_105',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_106',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_107',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_108',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_109',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_110',
            field=models.IntegerField(default=0, verbose_name='الإجراء الأول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_201',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_202',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_203',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_204',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_205',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_206',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_207',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_208',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_209',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='action_210',
            field=models.IntegerField(default=0, verbose_name='الإجراء الثاني'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='alarm_type',
            field=models.IntegerField(choices=[(0, 'لا يوجد'), (1, 'تسجيل تلقائي'), (2, 'تجربة تلقائية'), (4, 'فتح'), (5, 'إغلاق')], default=0, verbose_name='Alarm Type'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='code',
            field=models.CharField(db_index=True, max_length=16, validators=[django.core.validators.RegexValidator(message='الرمز غير صحيح', regex='^[ER](\\d+)$')], verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='decryption_type',
            field=models.IntegerField(choices=[(0, 'المنطقة'), (1, 'المستخدم')], default=0, verbose_name='نوع فك التشفير'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='description',
            field=models.CharField(max_length=40, verbose_name='الوصف'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='is_periodic',
            field=models.BooleanField(default=False, verbose_name='مجدول'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='partition',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='return_delay',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='device',
            name='name',
            field=models.CharField(max_length=30, unique=True, verbose_name='الإسم'),
        ),
        migrations.AlterField(
            model_name='device',
            name='type',
            field=models.CharField(choices=[('mcdi', 'MCDI'), ('surgard', 'SurGard')], max_length=10, verbose_name='النوع'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_friday',
            field=models.TimeField(blank=True, null=True, verbose_name='إغلاق'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_monday',
            field=models.TimeField(blank=True, null=True, verbose_name='إغلاق'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_saturday',
            field=models.TimeField(blank=True, null=True, verbose_name='إغلاق'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_sunday',
            field=models.TimeField(blank=True, null=True, verbose_name='إغلاق'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_thursday',
            field=models.TimeField(blank=True, null=True, verbose_name='إغلاق'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_tuesday',
            field=models.TimeField(blank=True, null=True, verbose_name='إغلاق'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='closing_wednesday',
            field=models.TimeField(blank=True, null=True, verbose_name='إغلاق'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_friday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_monday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_saturday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_sunday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_thursday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_tuesday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_closing_wednesday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_friday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_monday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_saturday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_sunday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_thursday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_tuesday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='delay_opning_wednesday',
            field=models.IntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_friday',
            field=models.TimeField(blank=True, null=True, verbose_name='فتح'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_monday',
            field=models.TimeField(blank=True, null=True, verbose_name='فتح'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_saturday',
            field=models.TimeField(blank=True, null=True, verbose_name='فتح'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_sunday',
            field=models.TimeField(blank=True, null=True, verbose_name='فتح'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_thursday',
            field=models.TimeField(blank=True, null=True, verbose_name='فتح'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_tuesday',
            field=models.TimeField(blank=True, null=True, verbose_name='فتح'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='opening_wednesday',
            field=models.TimeField(blank=True, null=True, verbose_name='فتح'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='partition',
            field=models.IntegerField(db_index=True, default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='القسم'),
        ),
    ]
