# Generated by Django 5.0.3 on 2024-04-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0010_alter_alarmcode_options_alter_device_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmcode',
            name='decryption_type',
            field=models.IntegerField(choices=[(0, 'المنطقة'), (1, 'مستهلك')], default=0, verbose_name='نوع فك التشفير'),
        ),
    ]
