# Generated by Django 5.0.3 on 2024-04-29 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_account_id_alter_historicalaccount_id'),
        ('configurations', '0011_alter_alarmcode_decryption_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmcode',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_codes', to='accounts.account', verbose_name='الحساب'),
        ),
    ]
