# Generated by Django 5.0.3 on 2024-04-29 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0012_alter_alarmcode_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alarmcode',
            name='return_delay',
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='return_delay_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AddField(
            model_name='alarmcode',
            name='return_delay_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='التأخير'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='periodic_interval_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعة'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='periodic_interval_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='دقيقة'),
        ),
    ]
