# Generated by Django 5.0.3 on 2024-04-29 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0013_remove_alarmcode_return_delay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alarmcode',
            name='has_return',
            field=models.BooleanField(default=False, verbose_name='Has Return'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='return_delay_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='ساعة'),
        ),
        migrations.AlterField(
            model_name='alarmcode',
            name='return_delay_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='دقيقة'),
        ),
    ]
