# Generated by Django 5.0.3 on 2024-03-17 14:20

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_historicalaccount_zone_and_more'),
        ('configurations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField()),
                ('decrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configurations.device')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='HistoricalDecryptedEvent',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('receiveer_no', models.IntegerField()),
                ('line_no', models.IntegerField()),
                ('partition', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(-1, 'locked'), (0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow')], db_index=True, default=0)),
                ('custom', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account')),
                ('alarm_code', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.alarmcode')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('locked_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accountuser')),
                ('zone', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.zone')),
                ('raw_event', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='events.rawevent')),
            ],
            options={
                'verbose_name': 'historical decrypted event',
                'verbose_name_plural': 'historical decrypted events',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='DecryptedEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiveer_no', models.IntegerField()),
                ('line_no', models.IntegerField()),
                ('partition', models.IntegerField(default=0)),
                ('success', models.BooleanField(default=False)),
                ('status', models.IntegerField(choices=[(-1, 'locked'), (0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow')], db_index=True, default=0)),
                ('custom', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField()),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account')),
                ('alarm_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.alarmcode')),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountuser')),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.zone')),
                ('raw_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.rawevent')),
            ],
            options={
                'ordering': ('-id',),
            },
        ),
    ]
