# Generated by Django 5.0.3 on 2024-03-17 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='protocole',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='protocole',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rawevent',
            name='has_errors',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='partition',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='success',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='partition',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='success',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='decrypted',
            field=models.BooleanField(db_index=True, default=False),
        ),
    ]
