# Generated by Django 5.0.3 on 2024-03-15 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='custom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='rawevent',
            name='decrypted',
            field=models.BooleanField(default=False),
        ),
    ]
