# Generated by Django 5.0.3 on 2024-03-14 17:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawevent',
            name='device_name',
        ),
        migrations.AddField(
            model_name='rawevent',
            name='device',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='configurations.device'),
            preserve_default=False,
        ),
    ]
