# Generated by Django 5.0.3 on 2024-03-15 23:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_zone'),
        ('configurations', '0002_alarmcode_type'),
        ('events', '0002_decryptedevent_custom_rawevent_decrypted'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='commit',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='pending',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='zone',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.zone'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='alarm_code',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.alarmcode'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountuser'),
        ),
    ]
