# Generated by Django 5.0.3 on 2024-04-19 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_options_alter_accountuser_options_and_more'),
        ('configurations', '0006_alter_alarmcode_options_alter_device_options_and_more'),
        ('events', '0003_alter_decryptedevent_custom_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decryptedevent',
            options={'ordering': ('-id',), 'verbose_name': 'Decrypted Event', 'verbose_name_plural': 'Decrypted Events'},
        ),
        migrations.AlterModelOptions(
            name='historicaldecryptedevent',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'تاريخ', 'verbose_name_plural': 'historical Decrypted Events'},
        ),
        migrations.AlterModelOptions(
            name='rawevent',
            options={'ordering': ('-id',), 'verbose_name': 'Raw Event', 'verbose_name_plural': 'Raw Events'},
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='alarm_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.alarmcode', verbose_name='Alarm Code'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='custom',
            field=models.BooleanField(default=True, verbose_name='Custom'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='line_no',
            field=models.IntegerField(default=-1, verbose_name='Line No'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked At'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Locked By'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='note',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='partition',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Partition'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='protocole',
            field=models.IntegerField(default=-1, verbose_name='Protocole'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='raw_event',
            field=models.IntegerField(verbose_name='Raw Event'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='receiveer_no',
            field=models.IntegerField(default=-1, verbose_name='Receiveer No'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='status',
            field=models.IntegerField(choices=[(-1, 'locked'), (0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow')], db_index=True, default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='success',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountuser', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='alarm_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.alarmcode', verbose_name='Alarm Code'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='created_at',
            field=models.DateTimeField(verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='custom',
            field=models.BooleanField(default=True, verbose_name='Custom'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='line_no',
            field=models.IntegerField(default=-1, verbose_name='Line No'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Locked At'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='locked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Locked By'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='note',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Note'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='partition',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Partition'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='protocole',
            field=models.IntegerField(default=-1, verbose_name='Protocole'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='raw_event',
            field=models.IntegerField(verbose_name='Raw Event'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='receiveer_no',
            field=models.IntegerField(default=-1, verbose_name='Receiveer No'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='status',
            field=models.IntegerField(choices=[(-1, 'locked'), (0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow')], db_index=True, default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='success',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Success'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='user',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.accountuser', verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='zone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.zone', verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='decrypted',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Decrypted'),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configurations.device', verbose_name='Device'),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='has_errors',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Has Errors'),
        ),
    ]
