# Generated by Django 5.0.3 on 2024-03-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_alter_decryptedevent_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptedevent',
            name='commit',
        ),
        migrations.RemoveField(
            model_name='decryptedevent',
            name='follow',
        ),
        migrations.RemoveField(
            model_name='decryptedevent',
            name='pending',
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Saved'), (1, 'Pending'), (2, 'Follow')], default=0),
        ),
    ]
