# Generated by Django 5.0.3 on 2024-04-21 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_alter_city_options_and_more'),
        ('events', '0004_alter_decryptedevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='account_note',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Account Note'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='account_note_timer',
            field=models.BooleanField(default=False, verbose_name='Account Note Timer'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='note_timer_interval_hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='note_timer_interval_minnutes',
            field=models.IntegerField(default=0, verbose_name='Minutes'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='timer',
            field=models.BooleanField(default=False, verbose_name='Timer'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='timer_interval_hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='timer_interval_minnutes',
            field=models.IntegerField(default=0, verbose_name='Minutes'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='account_note',
            field=models.TextField(blank=True, max_length=120, null=True, verbose_name='Account Note'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='account_note_timer',
            field=models.BooleanField(default=False, verbose_name='Account Note Timer'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='note_timer_interval_hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='note_timer_interval_minnutes',
            field=models.IntegerField(default=0, verbose_name='Minutes'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='timer',
            field=models.BooleanField(default=False, verbose_name='Timer'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='timer_interval_hours',
            field=models.IntegerField(default=0, verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='timer_interval_minnutes',
            field=models.IntegerField(default=0, verbose_name='Minutes'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='created_at',
            field=models.DateTimeField(verbose_name='أنشئ عند'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='حدّث عند'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='created_at',
            field=models.DateTimeField(verbose_name='أنشئ عند'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='حدّث عند'),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='أنشئ عند'),
        ),
    ]
