# Generated by Django 5.0.3 on 2024-03-16 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_remove_decryptedevent_commit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decryptedevent',
            name='status',
            field=models.IntegerField(choices=[(0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow')], default=0),
        ),
    ]
