# Generated by Django 5.0.3 on 2024-04-22 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_decryptedevent_account_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decryptedevent',
            name='account_note_timer',
            field=models.BooleanField(default=False, verbose_name='Timer'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='timer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Timer'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='account_note_timer',
            field=models.BooleanField(default=False, verbose_name='Timer'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='timer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Timer'),
        ),
    ]
