# Generated by Django 5.0.3 on 2024-04-25 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_decryptedevent_account_note_timer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='delayed_periodic',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Delayed Periodic'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='delayed_return',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Delayed Return'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='handled_periodic_delay',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Handled Periodic Delay'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='handled_return_delay',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Handled Return Delay'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='has_return',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Has Return'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='is_last_periodic_event',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Last Periodic Event'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='is_out_of_schedule',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Out Of Schedule'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='delayed_periodic',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Delayed Periodic'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='delayed_return',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Delayed Return'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='handled_periodic_delay',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Handled Periodic Delay'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='handled_return_delay',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Handled Return Delay'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='has_return',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Has Return'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='is_last_periodic_event',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Last Periodic Event'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='is_out_of_schedule',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Out Of Schedule'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='status',
            field=models.IntegerField(choices=[(-1, 'locked'), (0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow'), (4, 'Delayed Return'), (5, 'Delayed Periodic')], db_index=True, default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='status',
            field=models.IntegerField(choices=[(-1, 'locked'), (0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow'), (4, 'Delayed Return'), (5, 'Delayed Periodic')], db_index=True, default=0, verbose_name='Status'),
        ),
    ]
