# Generated by Django 5.0.3 on 2024-03-16 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_decryptedevent_status_historicaldecryptedevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='locked_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='locked_at',
            field=models.DateTimeField(null=True),
        ),
    ]
