# Generated by Django 5.0.3 on 2024-03-16 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicalaccount_delete_historicalaccountuser'),
        ('configurations', '0002_alarmcode_type'),
        ('events', '0008_decryptedevent_locked_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='note',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='note',
            field=models.TextField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.account'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='alarm_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.alarmcode'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.accountuser'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.zone'),
        ),
    ]
