# Generated by Django 5.0.3 on 2024-04-27 18:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accountuser_options_alter_zone_options_and_more'),
        ('configurations', '0010_alter_alarmcode_options_alter_device_options_and_more'),
        ('events', '0008_alter_historicaldecryptedevent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decryptedevent',
            name='account_note_timer',
            field=models.BooleanField(default=False, verbose_name='مؤقت'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='alarm_code',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='configurations.alarmcode', verbose_name='رمز الإنذار'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='partition',
            field=models.IntegerField(db_index=True, default=0, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='status',
            field=models.IntegerField(choices=[(-1, 'locked'), (0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow'), (4, 'Delayed Return'), (5, 'Delayed Periodic')], db_index=True, default=0, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='timer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مؤقت'),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='zone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.zone', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='account_note_timer',
            field=models.BooleanField(default=False, verbose_name='مؤقت'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='alarm_code',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='configurations.alarmcode', verbose_name='رمز الإنذار'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='partition',
            field=models.IntegerField(db_index=True, default=0, verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='status',
            field=models.IntegerField(choices=[(-1, 'locked'), (0, 'Not Saved'), (1, 'Saved'), (2, 'Pending'), (3, 'Follow'), (4, 'Delayed Return'), (5, 'Delayed Periodic')], db_index=True, default=0, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='timer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مؤقت'),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='zone',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.zone', verbose_name='المنطقة'),
        ),
        migrations.AlterField(
            model_name='rawevent',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='configurations.device', verbose_name='الجهاز'),
        ),
    ]
