# Generated by Django 5.0.3 on 2024-03-17 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_decryptedevent_note_historicaldecryptedevent_note_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='decryptedevent',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterModelOptions(
            name='rawevent',
            options={'ordering': ('-id',)},
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='locked_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='decryptedevent',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicaldecryptedevent',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
