# Generated by Django 5.0.3 on 2024-04-29 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_decryptedevent_raw_event_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='decryptedevent',
            name='custom',
        ),
        migrations.RemoveField(
            model_name='historicaldecryptedevent',
            name='custom',
        ),
    ]
