# Generated by Django 5.0.3 on 2024-04-29 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_remove_decryptedevent_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='is_user_holiday',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is User Holiday'),
        ),
        migrations.AddField(
            model_name='decryptedevent',
            name='is_user_out_of_schedule',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is User Out Of Schedule'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='is_user_holiday',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is User Holiday'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='is_user_out_of_schedule',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is User Out Of Schedule'),
        ),
    ]
