# Generated by Django 5.0.3 on 2024-04-30 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_decryptedevent_is_user_holiday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptedevent',
            name='handled_out_of_schedule',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Handled Out Of Schedule'),
        ),
        migrations.AddField(
            model_name='historicaldecryptedevent',
            name='handled_out_of_schedule',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Handled Out Of Schedule'),
        ),
    ]
