# Generated by Django 5.0.3 on 2024-04-30 06:02

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalServiceOrder',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'تم إنشاءه'), (1, 'تحت المراجعة'), (2, 'تحت التنفيذ'), (3, 'تم التنفيذ'), (-1, 'تم إلغاءه')], db_index=True, default=0, verbose_name='الحالة')),
                ('summary', models.CharField(max_length=120, verbose_name='الملخص')),
                ('request', models.TextField(verbose_name='الطلب')),
                ('internal_notes', models.TextField(blank=True, verbose_name='الملاحظات الداخلية')),
                ('response', models.TextField(blank=True, verbose_name='الجواب')),
                ('created_at', models.DateTimeField(blank=True, editable=False, verbose_name='أنشئ عند')),
                ('updated_at', models.DateTimeField(blank=True, editable=False, verbose_name='حدّث عند')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تم إغلاق الطلب عند')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account', verbose_name='الحساب')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'تاريخ الطلب',
                'verbose_name_plural': 'historical الطلبات',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'تم إنشاءه'), (1, 'تحت المراجعة'), (2, 'تحت التنفيذ'), (3, 'تم التنفيذ'), (-1, 'تم إلغاءه')], db_index=True, default=0, verbose_name='الحالة')),
                ('summary', models.CharField(max_length=120, verbose_name='الملخص')),
                ('request', models.TextField(verbose_name='الطلب')),
                ('internal_notes', models.TextField(blank=True, verbose_name='الملاحظات الداخلية')),
                ('response', models.TextField(blank=True, verbose_name='الجواب')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='أنشئ عند')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='حدّث عند')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تم إغلاق الطلب عند')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب')),
            ],
            options={
                'verbose_name': 'الطلب',
                'verbose_name_plural': 'الطلبات',
            },
        ),
    ]
