# Generated by Django 5.0.3 on 2024-04-21 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_account_options_alter_city_options_and_more'),
        ('support', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='account',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='أنشئ عند'),
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='أنشئ من'),
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='حدّث عند'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='الحساب'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='أنشئ عند'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='أنشئ من'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='حدّث عند'),
        ),
    ]
