# Generated by Django 5.0.3 on 2024-04-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_alter_historicalserviceorder_account_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalserviceorder',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'تاريخ الطلب', 'verbose_name_plural': 'historical الطلبات'},
        ),
        migrations.AlterModelOptions(
            name='serviceorder',
            options={'verbose_name': 'الطلب', 'verbose_name_plural': 'الطلبات'},
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تم إغلاق الطلب عند'),
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='الملاحظات الداخلية'),
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='request',
            field=models.TextField(verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='response',
            field=models.TextField(blank=True, verbose_name='الجواب'),
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'تم إنشاءه'), (1, 'تحت المراجعة'), (2, 'تحت التنفيذ'), (3, 'تم التنفيذ'), (-1, 'تم إلغاءه')], db_index=True, default=0, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='historicalserviceorder',
            name='summary',
            field=models.CharField(max_length=120, verbose_name='الملخص'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تم إغلاق الطلب عند'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='internal_notes',
            field=models.TextField(blank=True, verbose_name='الملاحظات الداخلية'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='request',
            field=models.TextField(verbose_name='الطلب'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='response',
            field=models.TextField(blank=True, verbose_name='الجواب'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'تم إنشاءه'), (1, 'تحت المراجعة'), (2, 'تحت التنفيذ'), (3, 'تم التنفيذ'), (-1, 'تم إلغاءه')], db_index=True, default=0, verbose_name='الحالة'),
        ),
        migrations.AlterField(
            model_name='serviceorder',
            name='summary',
            field=models.CharField(max_length=120, verbose_name='الملخص'),
        ),
    ]
