# Generated by Django 5.0.3 on 2024-04-29 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0003_alter_historicalserviceorder_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalserviceorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='serviceorder',
            name='created_by',
        ),
    ]
