# Generated by Django 5.0.2 on 2024-02-22 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configurations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='decryptionconfiguration',
            name='end_line',
            field=models.CharField(choices=[('<CR>', '<CR>'), ('<DC4>', '<DC4>')], default='<CR>', max_length=10),
            preserve_default=False,
        ),
    ]
