# Generated by Django 5.0.2 on 2024-03-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Partition',
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='account',
        ),
        migrations.AddField(
            model_name='account',
            name='account_users',
            field=models.ManyToManyField(blank=True, to='accounts.accountuser'),
        ),
    ]
