# Generated by Django 5.0.2 on 2024-03-04 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_delete_partition_remove_accountuser_account_and_more'),
    ]

    operations = [
    ]
