# Generated by Django 5.0.2 on 2024-03-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_accountuser_unique_id'),
    ]

    operations = [
    ]
