# Generated by Django 5.0.2 on 2024-03-04 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_accountuser_unique_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='account_users',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='account',
            field=models.ForeignKey(default=100, on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
            preserve_default=False,
        ),
    ]
