# Generated by Django 5.0.3 on 2024-03-08 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_account_users_accountuser_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='authorized_days_sat',
            field=models.BooleanField(default=False, verbose_name='Saturday'),
        ),
    ]
