# Generated by Django 5.0.3 on 2024-03-15 14:31

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='InstallationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30, verbose_name='Company Name')),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Phone Number 1')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Phone Number 2')),
            ],
            options={
                'verbose_name': 'Installation Companies',
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('address_line1', models.CharField(blank=True, max_length=30)),
                ('address_line2', models.CharField(blank=True, max_length=30)),
                ('address_line3', models.CharField(blank=True, max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('security_number', models.CharField(blank=True, max_length=20)),
                ('memo', models.TextField(blank=True, max_length=120)),
                ('police_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('police_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('police_number3', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('fire_dept_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('fire_dept_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('fire_dept_number3', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('emergency_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('emergency_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('emergency_number3', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('partition_name0', models.CharField(default='Default', max_length=30)),
                ('partition_name1', models.CharField(blank=True, max_length=30)),
                ('partition_name2', models.CharField(blank=True, max_length=30)),
                ('partition_name3', models.CharField(blank=True, max_length=30)),
                ('partition_name4', models.CharField(blank=True, max_length=30)),
                ('partition_name5', models.CharField(blank=True, max_length=30)),
                ('partition_name6', models.CharField(blank=True, max_length=30)),
                ('partition_name7', models.CharField(blank=True, max_length=30)),
                ('partition_name8', models.CharField(blank=True, max_length=30)),
                ('partition_name9', models.CharField(blank=True, max_length=30)),
                ('partition_name10', models.CharField(blank=True, max_length=30)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('installation_note', models.TextField(blank=True, max_length=120)),
                ('receiver_phone_number', models.CharField(blank=True, max_length=20)),
                ('transmitter_phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city')),
                ('installation_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.installationcompany')),
            ],
        ),
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('name', models.CharField(max_length=40)),
                ('in_out_codes', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('phone_number1', models.CharField(blank=True, max_length=20)),
                ('phone_number2', models.CharField(blank=True, max_length=20)),
                ('phone_number3', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('holiday_begins', models.DateField(blank=True, null=True)),
                ('holiday_ends', models.DateField(blank=True, null=True)),
                ('keypad_code', models.CharField(blank=True, max_length=6)),
                ('hot_user', models.BooleanField(default=False)),
                ('authorized_days_sat', models.BooleanField(default=False, verbose_name='Saturday')),
                ('authorized_days_sun', models.BooleanField(default=False)),
                ('authorized_days_mon', models.BooleanField(default=False)),
                ('authorized_days_tue', models.BooleanField(default=False)),
                ('authorized_days_wed', models.BooleanField(default=False)),
                ('authorized_days_thu', models.BooleanField(default=False)),
                ('authorized_days_fri', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='accountuser',
            constraint=models.UniqueConstraint(fields=('account', 'partition', 'name'), name='accounts.accountuser.unique_id'),
        ),
    ]
