# Generated by Django 5.0.3 on 2024-03-17 14:20

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccount',
            fields=[
                ('id', models.IntegerField(db_index=True)),
                ('name', models.CharField(max_length=40)),
                ('address_line1', models.CharField(blank=True, max_length=30)),
                ('address_line2', models.CharField(blank=True, max_length=30)),
                ('address_line3', models.CharField(blank=True, max_length=30)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('email', models.EmailField(blank=True, max_length=30)),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('whatsapp_number', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('security_number', models.CharField(blank=True, max_length=20)),
                ('memo', models.TextField(blank=True, max_length=120)),
                ('police_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('police_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('police_number3', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('fire_dept_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('fire_dept_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('fire_dept_number3', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('emergency_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('emergency_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('emergency_number3', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('partition_name0', models.CharField(default='Default', max_length=30)),
                ('partition_name1', models.CharField(blank=True, max_length=30)),
                ('partition_name2', models.CharField(blank=True, max_length=30)),
                ('partition_name3', models.CharField(blank=True, max_length=30)),
                ('partition_name4', models.CharField(blank=True, max_length=30)),
                ('partition_name5', models.CharField(blank=True, max_length=30)),
                ('partition_name6', models.CharField(blank=True, max_length=30)),
                ('partition_name7', models.CharField(blank=True, max_length=30)),
                ('partition_name8', models.CharField(blank=True, max_length=30)),
                ('partition_name9', models.CharField(blank=True, max_length=30)),
                ('partition_name10', models.CharField(blank=True, max_length=30)),
                ('installation_date', models.DateField(blank=True, null=True)),
                ('installation_note', models.TextField(blank=True, max_length=120)),
                ('receiver_phone_number', models.CharField(blank=True, max_length=20)),
                ('transmitter_phone_number', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
            ],
            options={
                'verbose_name': 'historical account',
                'verbose_name_plural': 'historical accounts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partition', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('name', models.CharField(max_length=30)),
                ('code', models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='accountuser',
            name='accounts.accountuser.unique_id',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='accountuser',
            constraint=models.UniqueConstraint(fields=('account', 'partition', 'code'), name='accounts.accountuser.unique_id'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.city'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='installation_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.installationcompany'),
        ),
        migrations.AddField(
            model_name='zone',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('account', 'partition', 'code'), name='accounts.zone.unique_id'),
        ),
    ]
