# Generated by Django 5.0.3 on 2024-05-02 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='copy_alarm_codes',
            field=models.BooleanField(default=False, verbose_name='نسخ الإنذارات'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='copy_alarm_codes',
            field=models.BooleanField(default=False, verbose_name='نسخ الإنذارات'),
        ),
    ]
