# Generated by Django 5.0.3 on 2024-03-16 17:41

import django.core.validators
import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAccountUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('partition', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('name', models.CharField(max_length=40)),
                ('in_out_codes', models.CharField(blank=True, max_length=20)),
                ('password', models.CharField(blank=True, max_length=15)),
                ('phone_number1', models.CharField(blank=True, max_length=20)),
                ('phone_number2', models.CharField(blank=True, max_length=20)),
                ('phone_number3', models.CharField(blank=True, max_length=20)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('holiday_begins', models.DateField(blank=True, null=True)),
                ('holiday_ends', models.DateField(blank=True, null=True)),
                ('keypad_code', models.CharField(blank=True, max_length=6)),
                ('hot_user', models.BooleanField(default=False)),
                ('authorized_days_sat', models.BooleanField(default=False, verbose_name='Saturday')),
                ('authorized_days_sun', models.BooleanField(default=False)),
                ('authorized_days_mon', models.BooleanField(default=False)),
                ('authorized_days_tue', models.BooleanField(default=False)),
                ('authorized_days_wed', models.BooleanField(default=False)),
                ('authorized_days_thu', models.BooleanField(default=False)),
                ('authorized_days_fri', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('account', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical account user',
                'verbose_name_plural': 'historical account users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
