# Generated by Django 5.0.3 on 2024-07-27 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_account_copy_alarm_codes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
    ]
