# Generated by Django 5.0.3 on 2024-03-13 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_account_installation_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='partition_name0',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
