# Generated by Django 5.0.3 on 2024-04-19 12:23

import django.core.validators
import django.db.models.deletion
import phonenumber_field.modelfields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_city_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
        migrations.AlterModelOptions(
            name='accountuser',
            options={'verbose_name': 'Account User', 'verbose_name_plural': 'Account Users'},
        ),
        migrations.AlterModelOptions(
            name='historicalaccount',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Account', 'verbose_name_plural': 'historical Accounts'},
        ),
        migrations.AlterModelOptions(
            name='installationcompany',
            options={'verbose_name': 'Installation Company', 'verbose_name_plural': 'Installation Companies'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'Zone', 'verbose_name_plural': 'Zones'},
        ),
        migrations.AddField(
            model_name='accountuser',
            name='title1',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title 1'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='title2',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title 2'),
        ),
        migrations.AddField(
            model_name='accountuser',
            name='title3',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title 3'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_line1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_line2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='address_line3',
            field=models.CharField(blank=True, max_length=30, verbose_name='Address Line 3'),
        ),
        migrations.AlterField(
            model_name='account',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='بريد إلكتروني'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emergency_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Emergency Number 1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emergency_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Emergency Number 2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emergency_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Emergency Number 3'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fire_dept_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Fire Dept Number 1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fire_dept_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Fire Dept Number 2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fire_dept_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Fire Dept Number 3'),
        ),
        migrations.AlterField(
            model_name='account',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='accounts', to='accounts.group', verbose_name='Groups'),
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='installation_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.installationcompany', verbose_name='Installation Company'),
        ),
        migrations.AlterField(
            model_name='account',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='account',
            name='installation_note',
            field=models.TextField(blank=True, max_length=120, verbose_name='Installation Note'),
        ),
        migrations.AlterField(
            model_name='account',
            name='memo',
            field=models.TextField(blank=True, max_length=120, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name0',
            field=models.CharField(default='Default', max_length=30, verbose_name='Partition Name 0'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name10',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 10'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name3',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 3'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name4',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 4'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name5',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 5'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name6',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 6'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name7',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 7'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name8',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 8'),
        ),
        migrations.AlterField(
            model_name='account',
            name='partition_name9',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 9'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Phone Number 1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Phone Number 2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='police_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Police Number 1'),
        ),
        migrations.AlterField(
            model_name='account',
            name='police_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Police Number 2'),
        ),
        migrations.AlterField(
            model_name='account',
            name='police_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Police Number 3'),
        ),
        migrations.AlterField(
            model_name='account',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Receiver Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='security_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Security Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='transmitter_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Transmitter Phone Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='account',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Whatsapp Number'),
        ),
        migrations.AlterField(
            model_name='account',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='authorized_days_fri',
            field=models.BooleanField(default=False, verbose_name='Friday'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='authorized_days_mon',
            field=models.BooleanField(default=False, verbose_name='Monday'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='authorized_days_sun',
            field=models.BooleanField(default=False, verbose_name='Sunday'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='authorized_days_thu',
            field=models.BooleanField(default=False, verbose_name='Thursday'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='authorized_days_tue',
            field=models.BooleanField(default=False, verbose_name='Tuesday'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='authorized_days_wed',
            field=models.BooleanField(default=False, verbose_name='Wednesday'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='code',
            field=models.IntegerField(verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='holiday_begins',
            field=models.DateField(blank=True, null=True, verbose_name='Holiday Begins'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='holiday_ends',
            field=models.DateField(blank=True, null=True, verbose_name='Holiday Ends'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='hot_user',
            field=models.BooleanField(default=False, verbose_name='Hot User'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='in_out_codes',
            field=models.CharField(blank=True, max_length=20, verbose_name='In-Out Codes'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='keypad_code',
            field=models.CharField(blank=True, max_length=6, verbose_name='Keypad Code'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='partition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Partition'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='password',
            field=models.CharField(blank=True, max_length=15, verbose_name='كلمة المرور'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='phone_number1',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number 1'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='phone_number2',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number 2'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone Number 3'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='title',
            field=models.CharField(blank=True, max_length=150, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='address_line1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='address_line2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='address_line3',
            field=models.CharField(blank=True, max_length=30, verbose_name='Address Line 3'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='city',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.city', verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='created_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='email',
            field=models.EmailField(blank=True, max_length=30, verbose_name='بريد إلكتروني'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='emergency_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Emergency Number 1'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='emergency_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Emergency Number 2'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='emergency_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Emergency Number 3'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='fire_dept_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Fire Dept Number 1'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='fire_dept_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Fire Dept Number 2'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='fire_dept_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Fire Dept Number 3'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='id',
            field=models.IntegerField(db_index=True, verbose_name='Account ID'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='installation_company',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.installationcompany', verbose_name='Installation Company'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='installation_date',
            field=models.DateField(blank=True, null=True, verbose_name='Installation Date'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='installation_note',
            field=models.TextField(blank=True, max_length=120, verbose_name='Installation Note'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='memo',
            field=models.TextField(blank=True, max_length=120, verbose_name='Memo'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Account Name'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name0',
            field=models.CharField(default='Default', max_length=30, verbose_name='Partition Name 0'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name1',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 1'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name10',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 10'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name2',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 2'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name3',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 3'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name4',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 4'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name5',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 5'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name6',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 6'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name7',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 7'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name8',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 8'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='partition_name9',
            field=models.CharField(blank=True, max_length=30, verbose_name='Partition Name 9'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='phone_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Phone Number 1'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Phone Number 2'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='police_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Police Number 1'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='police_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Police Number 2'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='police_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Police Number 3'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Receiver Phone Number'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='security_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Security Number'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='transmitter_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Transmitter Phone Number'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='updated_at',
            field=models.DateTimeField(blank=True, editable=False, verbose_name='Updated At'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Whatsapp Number'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='Zip Code'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.account', verbose_name='Account'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.IntegerField(verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='partition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='Partition'),
        ),
    ]
