# Generated by Django 5.0.3 on 2024-03-17 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_historicalaccount_delete_historicalaccountuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='partition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddConstraint(
            model_name='zone',
            constraint=models.UniqueConstraint(fields=('account', 'partition', 'code'), name='accounts.zone.unique_id'),
        ),
    ]
