# Generated by Django 5.0.3 on 2024-03-13 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_account_partition_name0'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='partition_name0',
            field=models.CharField(default='Default', max_length=30),
        ),
    ]
