# Generated by Django 5.0.3 on 2024-03-17 12:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_zone_partition_zone_accounts_zone_unique_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='accountuser',
            name='accounts.accountuser.unique_id',
        ),
        migrations.AddField(
            model_name='accountuser',
            name='code',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='accountuser',
            constraint=models.UniqueConstraint(fields=('account', 'partition', 'code'), name='accounts.accountuser.unique_id'),
        ),
    ]
