# Generated by Django 5.0.3 on 2024-03-13 10:26

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_account_phone_number1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=30)),
                ('phone_number1', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
                ('phone_number2', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='installation_company_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='installation_company_phone_number1',
        ),
        migrations.RemoveField(
            model_name='account',
            name='installation_company_phone_number2',
        ),
        migrations.AlterField(
            model_name='account',
            name='emergency_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emergency_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='emergency_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fire_dept_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fire_dept_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='fire_dept_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='police_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='police_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='police_number3',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='whatsapp_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY'),
        ),
        migrations.AddField(
            model_name='account',
            name='installation_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.installationcompany'),
        ),
    ]
