# Generated by Django 5.0.3 on 2024-04-22 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rename_note_timer_interval_hours_accountnote_timer_interval_hours_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountnote',
            old_name='timer_interval_minnutes',
            new_name='timer_interval_minutes',
        ),
    ]
