# Generated by Django 5.0.3 on 2024-03-14 17:43

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_installationcompany_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='installationcompany',
            options={'verbose_name': 'Installation Companies'},
        ),
        migrations.AlterField(
            model_name='installationcompany',
            name='name',
            field=models.CharField(blank=True, max_length=30, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='installationcompany',
            name='phone_number1',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Phone Number 1'),
        ),
        migrations.AlterField(
            model_name='installationcompany',
            name='phone_number2',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=20, region='SY', verbose_name='Phone Number 2'),
        ),
    ]
