# Generated by Django 5.0.3 on 2024-04-22 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_timer_interval_minnutes_accountnote_timer_interval_minutes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='copy_alarm_codes',
            field=models.BooleanField(default=False, verbose_name='Copy Alarm Codes'),
        ),
        migrations.AddField(
            model_name='account',
            name='copy_alarm_codes_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.account', verbose_name='Copy Alarm Codes From'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='copy_alarm_codes',
            field=models.BooleanField(default=False, verbose_name='Copy Alarm Codes'),
        ),
        migrations.AddField(
            model_name='historicalaccount',
            name='copy_alarm_codes_from',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='accounts.account', verbose_name='Copy Alarm Codes From'),
        ),
    ]
