# Generated by Django 5.0.3 on 2024-04-27 18:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_historicalaccount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountuser',
            options={'verbose_name': 'مستهلك', 'verbose_name_plural': 'المستهلكين'},
        ),
        migrations.AlterModelOptions(
            name='zone',
            options={'verbose_name': 'المنطقة', 'verbose_name_plural': 'المناطق'},
        ),
        migrations.RemoveField(
            model_name='accountuser',
            name='title',
        ),
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, verbose_name='معرف الحساب'),
        ),
        migrations.AlterField(
            model_name='account',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم المستقبل'),
        ),
        migrations.AlterField(
            model_name='account',
            name='transmitter_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم المرسل'),
        ),
        migrations.AlterField(
            model_name='accountnote',
            name='timer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='مؤقت'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='code',
            field=models.IntegerField(verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='holiday_begins',
            field=models.DateField(blank=True, null=True, verbose_name='بداية العطلة'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='holiday_ends',
            field=models.DateField(blank=True, null=True, verbose_name='نهاية العطلة'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='name',
            field=models.CharField(max_length=40, verbose_name='الإسم'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='partition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='القسم'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='phone_number3',
            field=models.CharField(blank=True, max_length=20, verbose_name='الرقم الثالث'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='title1',
            field=models.CharField(blank=True, max_length=150, verbose_name='التعريف'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='title2',
            field=models.CharField(blank=True, max_length=150, verbose_name='التعريف'),
        ),
        migrations.AlterField(
            model_name='accountuser',
            name='title3',
            field=models.CharField(blank=True, max_length=150, verbose_name='التعريف'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='id',
            field=models.IntegerField(db_index=True, verbose_name='معرف الحساب'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم المستقبل'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='transmitter_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='رقم المرسل'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='code',
            field=models.IntegerField(verbose_name='الرمز'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='name',
            field=models.CharField(max_length=30, verbose_name='الإسم'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='partition',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='القسم'),
        ),
    ]
