# Generated by Django 5.0.3 on 2024-04-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_accountuser_options_alter_zone_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountnote',
            name='decrypted_event',
            field=models.PositiveBigIntegerField(default=-1, verbose_name='Decrypted Event'),
        ),
    ]
