# Generated by Django 5.0.3 on 2024-04-29 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accountnote_decrypted_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.PositiveIntegerField(primary_key=True, serialize=False, verbose_name='معرف الحساب'),
        ),
        migrations.AlterField(
            model_name='historicalaccount',
            name='id',
            field=models.PositiveIntegerField(db_index=True, verbose_name='معرف الحساب'),
        ),
    ]
