version: '3.8'
services:
  redis:
    image: docker.io/redis/redis-stack-server:7.2.0-v9
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

  postgres:
    image: docker.io/postgres:latest
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: postgres # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: postgres # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: SMS # The PostgreSQL default database (automatically created at first launch)

#  pgadmin:
#    image: docker.io/dpage/pgadmin4:latest
#    environment:
#      PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
#      PGADMIN_DEFAULT_PASSWORD: password
#      PGADMIN_LISTEN_PORT: 80
#    ports:
#      - 15432:80
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    depends_on:
#      - postgres

volumes:
  pg-data:
  redis_data:
  pgadmin:
 