version: '3.8'
services:
  redis:
    image: redis/redis-stack-server:7.2.0-v9
    ports:
      - 6379:6379
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
    volumes:
      - redis_data:/data

  database:
    image: 'postgres:latest'
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
      POSTGRES_DB: test # The PostgreSQL default database (automatically created at first launch)

volumes:
  pg-data:
  redis_data:
 