# Generated by Django 5.0.3 on 2024-03-09 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_accountuser_authorized_days_sat'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstallationCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phone_number1', models.CharField(blank=True, max_length=20)),
                ('phone_number2', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='installation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='installation_note',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='account',
            name='receiver_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='transmitter_phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='account',
            name='installation_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.installationcompany'),
        ),
    ]
